---
driver:
  name: "terraform"
  root_module_directory: "examples/test"
  command_timeout: 3600

provisioner:
  name: "terraform"

platforms:
  - name: "aws"

verifier:
  name: "awspec"

suites:
  - name: "default"
    verifier:
      name: "awspec"
      patterns:
      - "examples/test/awspec.rb"